Drop the py26 and py27 in tox.ini file
release-engineering/dockpulp pull request #218
Opened 2023-02-21 02:44 UTC by LinglingXiang

1.Drop the support of python 2.6 and python 2.7

2023-02-21 02:44 UTC, LinglingXiang commented
@rbikar , please help review, thanks

2023-02-22 10:59 UTC, rbikar requested changes

2023-02-22 10:59 UTC, rbikar commented on .travis.yml
> +   - python: "3.6"
it looks like this has wrong indentation

2023-02-28 11:46 UTC, rbikar requested changes

2023-02-28 11:46 UTC, rbikar commented on .travis.yml
>      - python: "2.7"
I guess you could use python3 here as well.

2023-03-01 11:39 UTC, rbikar requested changes

2023-03-01 11:39 UTC, rbikar commented on .github/ISSUE_TEMPLATE.md
> +Please raise issues via the [new interface](./../issues/new/choose)
This file is not needed, please don't add it.

2023-03-01 11:39 UTC, rbikar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +---
This file is not needed, please don't add it.

2023-03-01 11:39 UTC, rbikar commented on .github/ISSUE_TEMPLATE/feature_request.md
> +---
This file not needed, please don't add it.

2023-03-01 11:39 UTC, rbikar commented on .github/ISSUE_TEMPLATE/question_support.md
> +---
This is not needed, please don't add it.

2023-03-01 11:39 UTC, rbikar commented on .github/workflows/release.yml
> +name: Release on PyPI
This is not needed, we have never created a package of dockpulp on pypi.

2023-03-01 11:39 UTC, rbikar commented on .github/workflows/tox-test.yml
> +          token: ${{ secrets.CODECOV_TOKEN }}
token shouldn't be needed for public repos

2023-03-01 11:39 UTC, rbikar commented on .github/workflows/tox-test.yml
> +name: Tox tests
if you want to add actions with:
- ` tox -e static` or `tox -e pidiff` (which is likely not needed) or `tox -e docs` you need to define them in tox.ini
 
But I think we only need actions with:
-  `tox -e py38`
-  `tox -e py39`
-  `tox -e flake8`

2023-03-01 11:39 UTC, rbikar commented on test-requirements.txt
> +pytest==3.2.5
what actually uses this file?

2023-03-02 07:47 UTC, rbikar requested changes

2023-03-02 07:47 UTC, rbikar commented on .github/workflows/tox-test.yml
> +        run: tox -e cov
this env is not define in tox.ini.
Either remove this `coverage`  check or add env definition to tox.ini.

2023-03-02 07:47 UTC, rbikar commented on test-requirements.txt
> +pytest==3.2.5
Is this file really required?

2023-03-04 09:35 UTC, LinglingXiang commented
@rbikar all the errors fixed, please help review again

2023-03-06 16:24 UTC, rbikar requested changes

2023-03-20 14:18 UTC, rbikar commented
@LinglingXiang 
The related PR was merged, please rebase this PR on current master and also address the issue where I added comment.

2023-03-21 02:07 UTC, closed without merging